# Generated by Django 3.2 on 2021-04-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210419_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='content',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
